# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: DNS_Name
    default: 'env-dnsname'
  - name: Keyvault
    default: 'certsecretmanagement'


steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'GSPipelines'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az keyvault secret set --name ${{parameters.DNS_Name}}-pkey-password --vault-name ${{parameters.Keyvault}} --value  $(Generating_CSR_and_Private_Key_and_install_azure_cli.GlobalGeneratedPassword) '
  workingDirectory: '$(Build.ArtifactStagingDirectory)' 


- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'GSPipelines'
    KeyVaultName: 'certsecretmanagement'
    SecretsFilter: '${{parameters.DNS_Name}}-pkey-password'
    RunAsPreJob: false


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'Certificate' 
    publishLocation: 'Container'
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional
  displayName: 'Run a one-line script'
