# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: windows-latest

parameters:
  - name: DNS_Name
    default: 'env-dnsname'
  - name: Keyvault
    default: 'certsecretmanagement'


steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'GSPipelines'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
     az keyvault certificate get-default-policy
     $defaultJsonPolicy = az keyvault certificate get-default-policy | convertfrom-json
     $defaultJsonPolicy.x509CertificateProperties.subject = "/C=GB/ST=London/L=London/O=AXAXL/OU=Global Technology/CN=${{parameters.DNS_Name}}"
    # write-host "this is it before converting to JSON: "$defaultJsonPolicy.x509CertificateProperties.subject
     $customJsonPolicy = $defaultJsonPolicy | convertto-json -depth 9 
    # write-host "This is after:" $customJsonPolicy
     az --% keyvault certificate create --vault-name ${{parameters.Keyvault}} --name ${{parameters.DNS_Name}} --policy $customJsonPolicy
  

#- task: PublishBuildArtifacts@1
#  inputs:
#    pathToPublish: '$(Build.ArtifactStagingDirectory)' 
#    artifactName: 'Certificate' 
#    publishLocation: 'Container'
#    #targetPath: # Required when publishLocation == FilePath
#    #parallel: false # Optional
#    #parallelCount: # Optional
#  displayName: 'Run a one-line script'
