pool:
  vmImage: windows-latest

parameters:
# Name it shows up with in the Keyvault
  - name: Cert_DNS_Name
    default: 'EnterCertificateNameHere'
# Name of the Certificate that is also put in the CN of the certificate
  - name: CA_DNS_Name
    default: 'EnterCertificateDNSNamehere'
# Name of the Keyvault to be used
  - name: Keyvault
    default: 'EnterKeyvaultNameHere'

steps:
- task: AzurePowerShell@5
  name: 'Generating_CSR_Request'
  inputs:
    azureSubscription: 'GSPipelines'
    ScriptType: 'InlineScript'
    Inline: |
      $CustomPolicy = New-AzKeyVaultCertificatePolicy -SubjectName "C=GB,ST=London,L=London,O=AXAXL,OU=Global Technology,CN=${{parameters.CA_DNS_Name}}" -ValidityInMonths 12  -IssuerName Unknown -EmailAtNumberOfDaysBeforeExpiry 30
      $customcert = Add-AzKeyVaultCertificate -VaultName ${{parameters.Keyvault}} -name ${{parameters.Cert_DNS_Name}} -CertificatePolicy $CustomPolicy
      write-host "Certificate Request has been generated in keyvault ${{parameters.Keyvault}} "
    workingDirectory: $(Build.ArtifactStagingDirectory)
    azurePowerShellVersion : LatestVersion

  displayName: 'Run a one-line script'




